name: deploy

on:
  push:
    branches:
      - main


jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checking directory
      run: ls -lah

    - name: Checking secret
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" >> ssh-key.pem
        chmod 400 ssh-key.pem

    # - name: Copy to server
    #   run: scp -i ssh-key.pem -o StrictHostKeyChecking=no index.html ubuntu@3.109.213.74:./
    

    - name: SSH to server and pull from GitHub
      run: |
         ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@3.109.213.74 << 'EOF'
           cd /var/www/html
           git config --global --add safe.directory /var/www/html
           if [ -d .git ]; then
             git pull origin main
           else
             echo "Error: Not  git repo"
             exit 1
           fi
         EOF
