name: deploy

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v4
        

      - name: checking secrets
        env: 
          SSH_KEY: ${{secrets.SSH_KEY}}
        run: | 
          echo "$SSH_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem

      - name: copy to server 
        run: scp -i ssh-key.pem -o StrictHostKeyChecking=no index.html ubuntu@3.109.213.74:./

      - name: SSh server
        run: ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@3.109.213.74"sudo cp index.html    /var/www/html"

        